### PR TITLE
fix(command-not-found): nix command suggestions

### LINKED ISSUE #185: `command-not-found` prints out wrong `nix run` command
On a flakified system, the interactive shell CNF handler responds with something like
```
The program 'ff2png' is currently not installed. You can install it
by typing:
  nix profile install nixpkgs#farbfeld.out

Or run it once with:
  nix run nixpkgs#farbfeld.out --command ...
```
It does not appear as though `--command` is a flag for `nix run`. `nix shell` however has such a flag, so the message could be
`nix shell nixpkgs#farbfeld.out --command ...`

OS: NixOS 22.05
Nix: 2.8.1, 2.9.1

### PR DESCRIPTION
**Pull request by figsoda**
closes #185

### CODE REVIEW

**Comment by doronbehar** [comment]
The issue fixed here has annoyed me for a while now... Is there a chance for a new release? :pray:

**Comment by figsoda** [comment]
@nix-community/nix-index any objections before I acreate a new release?

**Comment by bennofs** [comment]
No objections. Release process is as follows: 

1. Update changelog
2. Create annotated tag with changes for releases (git tag -a, see prev tags)
3. Create release on github for this tag
4. Publish release to crates.io
5. Bump version and prepare empty changelog for next release

**Comment by bennofs** [comment]
I can add you if you tell me your nicks on crates.io

**Comment by figsoda** [comment]
[figsoda](https://crates.io/users/figsoda) (same as github)

**Comment by figsoda** [comment]
Thanks for the invite, I'll do a release soon

**Comment by figsoda** [comment]
0.1.7 has been released :tada:

**Comment by doronbehar** [comment]
For reference https://nixpk.gs/pr-tracker.html?pr=251199

**Pull request merged**
